import {
  Rocket,
  Monitor,
  Megaphone,
  Wrench,
  Smartphone,
  ShoppingCart,
  Shield,
  Database,
} from "lucide-react";

export const initialWorkspaces = [
  {
    id: 1,
    icon: Rocket,
    iconBg: "#f4638a",
    title: "Mobile App Launch",
    description: "Revamping and launching our mobile application",
    progress: 72,
    progressColor: "#f4638a",
    tasks: 24,
    members: 8,
    updatedText: "Updated 2h ago",
  },
  {
    id: 2,
    icon: Monitor,
    iconBg: "#4d8dfa",
    title: "Website Redesign",
    description: "Redesigning company website for better UX",
    progress: 48,
    progressColor: "#4d8dfa",
    tasks: 18,
    members: 6,
    updatedText: "Updated 5h ago",
  },
  {
    id: 3,
    icon: Megaphone,
    iconBg: "#8a6bf5",
    title: "Marketing Campaign",
    description: "Q2 marketing campaign planning and execution",
    progress: 33,
    progressColor: "#8a6bf5",
    tasks: 12,
    members: 4,
    updatedText: "Updated 1d ago",
  },
  {
    id: 4,
    icon: Wrench,
    iconBg: "#34c98f",
    title: "Internal Tools",
    description: "Building internal tools to improve productivity",
    progress: 65,
    progressColor: "#34c98f",
    tasks: 16,
    members: 5,
    updatedText: "Updated 3h ago",
  },
  {
    id: 5,
    icon: Smartphone,
    iconBg: "#f5a623",
    title: "iOS Migration",
    description: "Migrating legacy features to the new iOS architecture",
    progress: 41,
    progressColor: "#f5a623",
    tasks: 21,
    members: 7,
    updatedText: "Updated 6h ago",
  },
  {
    id: 6,
    icon: ShoppingCart,
    iconBg: "#e85aad",
    title: "E-Commerce Platform",
    description: "Improving checkout, payments and shopping experience",
    progress: 57,
    progressColor: "#e85aad",
    tasks: 29,
    members: 9,
    updatedText: "Updated 1h ago",
  },
  {
    id: 7,
    icon: Shield,
    iconBg: "#5b8def",
    title: "Security Audit",
    description: "Auditing application security and fixing vulnerabilities",
    progress: 26,
    progressColor: "#5b8def",
    tasks: 15,
    members: 4,
    updatedText: "Updated 8h ago",
  },
  {
    id: 8,
    icon: Database,
    iconBg: "#20b486",
    title: "Data Infrastructure",
    description: "Improving databases, analytics and data pipelines",
    progress: 81,
    progressColor: "#20b486",
    tasks: 32,
    members: 10,
    updatedText: "Updated 30m ago",
  },
];
export const tasks = [
  // MOBILE APP LAUNCH - workspaceId: 1
  {
    id: 1,
    workspaceId: 1,
    title: "Finalize onboarding flow",
    status: "In Progress",
    priority: "High",
    due: "Today",
    color: "#f4638a",
  },
  {
    id: 2,
    workspaceId: 1,
    title: "Fix login API validation",
    status: "Todo",
    priority: "High",
    due: "Aug 26",
    color: "#f4638a",
  },
  {
    id: 3,
    workspaceId: 1,
    title: "Implement biometric login",
    status: "In Progress",
    priority: "High",
    due: "Aug 27",
    color: "#f4638a",
  },
  {
    id: 4,
    workspaceId: 1,
    title: "Design push notification settings",
    status: "Todo",
    priority: "Medium",
    due: "Aug 28",
    color: "#f4638a",
  },
  {
    id: 5,
    workspaceId: 1,
    title: "Add dark mode support",
    status: "Done",
    priority: "Medium",
    due: "Aug 22",
    color: "#f4638a",
  },
  {
    id: 6,
    workspaceId: 1,
    title: "Optimize app startup time",
    status: "In Progress",
    priority: "High",
    due: "Aug 29",
    color: "#f4638a",
  },

  // WEBSITE REDESIGN - workspaceId: 2
  {
    id: 7,
    workspaceId: 2,
    title: "Design landing page",
    status: "Done",
    priority: "Medium",
    due: "Aug 24",
    color: "#4d8dfa",
  },
  {
    id: 8,
    workspaceId: 2,
    title: "Review responsive breakpoints",
    status: "In Progress",
    priority: "Medium",
    due: "Aug 28",
    color: "#4d8dfa",
  },
  {
    id: 9,
    workspaceId: 2,
    title: "Build navigation component",
    status: "Done",
    priority: "High",
    due: "Aug 23",
    color: "#4d8dfa",
  },
  {
    id: 10,
    workspaceId: 2,
    title: "Update typography system",
    status: "Todo",
    priority: "Low",
    due: "Aug 30",
    color: "#4d8dfa",
  },
  {
    id: 11,
    workspaceId: 2,
    title: "Improve accessibility labels",
    status: "Todo",
    priority: "Medium",
    due: "Sep 01",
    color: "#4d8dfa",
  },
  {
    id: 12,
    workspaceId: 2,
    title: "Optimize mobile navigation",
    status: "In Progress",
    priority: "High",
    due: "Aug 29",
    color: "#4d8dfa",
  },

  // MARKETING CAMPAIGN - workspaceId: 3
  {
    id: 13,
    workspaceId: 3,
    title: "Plan Q2 social calendar",
    status: "Todo",
    priority: "Low",
    due: "Sep 02",
    color: "#8a6bf5",
  },
  {
    id: 14,
    workspaceId: 3,
    title: "Create Instagram campaign",
    status: "In Progress",
    priority: "High",
    due: "Aug 27",
    color: "#8a6bf5",
  },
  {
    id: 15,
    workspaceId: 3,
    title: "Write email campaign copy",
    status: "Todo",
    priority: "Medium",
    due: "Aug 28",
    color: "#8a6bf5",
  },
  {
    id: 16,
    workspaceId: 3,
    title: "Design campaign banners",
    status: "Done",
    priority: "Medium",
    due: "Aug 21",
    color: "#8a6bf5",
  },
  {
    id: 17,
    workspaceId: 3,
    title: "Set up campaign analytics",
    status: "Todo",
    priority: "High",
    due: "Sep 04",
    color: "#8a6bf5",
  },
  {
    id: 18,
    workspaceId: 3,
    title: "Prepare launch announcement",
    status: "In Progress",
    priority: "Medium",
    due: "Aug 30",
    color: "#8a6bf5",
  },

  // INTERNAL TOOLS - workspaceId: 4
  {
    id: 19,
    workspaceId: 4,
    title: "Create analytics dashboard",
    status: "Done",
    priority: "High",
    due: "Aug 23",
    color: "#34c98f",
  },
  {
    id: 20,
    workspaceId: 4,
    title: "Build employee directory",
    status: "In Progress",
    priority: "Medium",
    due: "Aug 29",
    color: "#34c98f",
  },
  {
    id: 21,
    workspaceId: 4,
    title: "Implement role permissions",
    status: "In Progress",
    priority: "High",
    due: "Aug 27",
    color: "#34c98f",
  },
  {
    id: 22,
    workspaceId: 4,
    title: "Add CSV export",
    status: "Todo",
    priority: "Low",
    due: "Sep 03",
    color: "#34c98f",
  },
  {
    id: 23,
    workspaceId: 4,
    title: "Improve search performance",
    status: "In Progress",
    priority: "High",
    due: "Aug 31",
    color: "#34c98f",
  },
  {
    id: 24,
    workspaceId: 4,
    title: "Fix notification preferences",
    status: "Done",
    priority: "Medium",
    due: "Aug 20",
    color: "#34c98f",
  },

  // IOS MIGRATION - workspaceId: 5
  {
    id: 25,
    workspaceId: 5,
    title: "Migrate authentication module",
    status: "In Progress",
    priority: "High",
    due: "Sep 01",
    color: "#f5a623",
  },
  {
    id: 26,
    workspaceId: 5,
    title: "Update networking layer",
    status: "Todo",
    priority: "High",
    due: "Sep 04",
    color: "#f5a623",
  },
  {
    id: 27,
    workspaceId: 5,
    title: "Migrate local storage",
    status: "In Progress",
    priority: "Medium",
    due: "Aug 30",
    color: "#f5a623",
  },
  {
    id: 28,
    workspaceId: 5,
    title: "Update notification service",
    status: "In Progress",
    priority: "Medium",
    due: "Sep 02",
    color: "#f5a623",
  },
  {
    id: 29,
    workspaceId: 5,
    title: "Remove deprecated APIs",
    status: "Done",
    priority: "Low",
    due: "Aug 19",
    color: "#f5a623",
  },
  {
    id: 30,
    workspaceId: 5,
    title: "Test iOS 19 compatibility",
    status: "Todo",
    priority: "High",
    due: "Sep 05",
    color: "#f5a623",
  },

  // E-COMMERCE PLATFORM - workspaceId: 6
  {
    id: 31,
    workspaceId: 6,
    title: "Redesign checkout flow",
    status: "In Progress",
    priority: "High",
    due: "Aug 29",
    color: "#e85aad",
  },
  {
    id: 32,
    workspaceId: 6,
    title: "Fix payment timeout issue",
    status: "In Progress",
    priority: "High",
    due: "Today",
    color: "#e85aad",
  },
  {
    id: 33,
    workspaceId: 6,
    title: "Add wishlist functionality",
    status: "Todo",
    priority: "Medium",
    due: "Sep 06",
    color: "#e85aad",
  },
  {
    id: 34,
    workspaceId: 6,
    title: "Improve product filtering",
    status: "In Progress",
    priority: "Medium",
    due: "Sep 01",
    color: "#e85aad",
  },
  {
    id: 35,
    workspaceId: 6,
    title: "Implement discount codes",
    status: "Done",
    priority: "High",
    due: "Aug 18",
    color: "#e85aad",
  },
  {
    id: 36,
    workspaceId: 6,
    title: "Fix cart persistence bug",
    status: "Done",
    priority: "High",
    due: "Aug 27",
    color: "#e85aad",
  },

  // SECURITY AUDIT - workspaceId: 7
  {
    id: 37,
    workspaceId: 7,
    title: "Audit authentication endpoints",
    status: "In Progress",
    priority: "High",
    due: "Aug 26",
    color: "#5b8def",
  },
  {
    id: 38,
    workspaceId: 7,
    title: "Review API permissions",
    status: "Todo",
    priority: "High",
    due: "Aug 28",
    color: "#5b8def",
  },
  {
    id: 39,
    workspaceId: 7,
    title: "Fix insecure password reset",
    status: "In Progress",
    priority: "High",
    due: "Today",
    color: "#5b8def",
  },
  {
    id: 40,
    workspaceId: 7,
    title: "Scan third-party dependencies",
    status: "In Progress",
    priority: "High",
    due: "Aug 30",
    color: "#5b8def",
  },
  {
    id: 41,
    workspaceId: 7,
    title: "Update security headers",
    status: "Done",
    priority: "Medium",
    due: "Aug 22",
    color: "#5b8def",
  },
  {
    id: 42,
    workspaceId: 7,
    title: "Document security policies",
    status: "Todo",
    priority: "Low",
    due: "Sep 07",
    color: "#5b8def",
  },

  // DATA INFRASTRUCTURE - workspaceId: 8
  {
    id: 43,
    workspaceId: 8,
    title: "Optimize PostgreSQL queries",
    status: "Done",
    priority: "High",
    due: "Aug 21",
    color: "#20b486",
  },
  {
    id: 44,
    workspaceId: 8,
    title: "Build analytics pipeline",
    status: "In Progress",
    priority: "High",
    due: "Aug 30",
    color: "#20b486",
  },
  {
    id: 45,
    workspaceId: 8,
    title: "Set up Redis caching",
    status: "In Progress",
    priority: "Medium",
    due: "Aug 28",
    color: "#20b486",
  },
  {
    id: 46,
    workspaceId: 8,
    title: "Create database backup strategy",
    status: "Todo",
    priority: "High",
    due: "Sep 01",
    color: "#20b486",
  },
  {
    id: 47,
    workspaceId: 8,
    title: "Improve data ingestion speed",
    status: "In Progress",
    priority: "High",
    due: "Sep 03",
    color: "#20b486",
  },
  {
    id: 48,
    workspaceId: 8,
    title: "Document data architecture",
    status: "Done",
    priority: "Low",
    due: "Aug 17",
    color: "#20b486",
  },
];