import {
  Rocket,
  Monitor,
  Megaphone,
  Wrench,
  Smartphone,
  ShoppingCart,
  Shield,
  Database,
} from "lucide-react";

export const initialWorkspaces = [
  {
    id: 1,
    icon: Rocket,
    iconBg: "#f4638a",
    title: "Personal Portfolio",
    description: "Building a portfolio to showcase projects and skills",
    progress: 68,
    progressColor: "#f4638a",
    tasks: 18,
    updatedText: "Updated 2h ago",
  },
  {
    id: 2,
    icon: Monitor,
    iconBg: "#4d8dfa",
    title: "Capstone Project",
    description: "Building a full-stack project management application",
    progress: 54,
    progressColor: "#4d8dfa",
    tasks: 32,
    updatedText: "Updated 1h ago",
  },
  {
    id: 3,
    icon: Megaphone,
    iconBg: "#8a6bf5",
    title: "Content Creation",
    description: "Planning videos, posts and personal tech content",
    progress: 37,
    progressColor: "#8a6bf5",
    tasks: 16,
    updatedText: "Updated 5h ago",
  },
  {
    id: 4,
    icon: Wrench,
    iconBg: "#34c98f",
    title: "Learn React",
    description: "Improving React skills through projects and practice",
    progress: 76,
    progressColor: "#34c98f",
    tasks: 22,
    updatedText: "Updated 3h ago",
  },
  {
    id: 5,
    icon: Smartphone,
    iconBg: "#f5a623",
    title: "AI Side Project",
    description: "Experimenting with AI features and local AI tools",
    progress: 42,
    progressColor: "#f5a623",
    tasks: 20,
    updatedText: "Updated 6h ago",
  },
  {
    id: 6,
    icon: ShoppingCart,
    iconBg: "#e85aad",
    title: "Freelance Website",
    description: "Designing and developing a website for a client",
    progress: 61,
    progressColor: "#e85aad",
    tasks: 24,
    updatedText: "Updated 4h ago",
  },
  {
    id: 7,
    icon: Shield,
    iconBg: "#5b8def",
    title: "Job Preparation",
    description: "Preparing projects, resume and skills for job applications",
    progress: 49,
    progressColor: "#5b8def",
    tasks: 19,
    updatedText: "Updated 8h ago",
  },
  {
    id: 8,
    icon: Database,
    iconBg: "#20b486",
    title: "Personal Learning",
    description: "Learning new technologies and strengthening fundamentals",
    progress: 73,
    progressColor: "#20b486",
    tasks: 27,
    updatedText: "Updated 30m ago",
  },
];

export const tasks = [
  // =========================
  // PERSONAL PORTFOLIO
  // workspaceId: 1
  // =========================

  {
    id: 1,
    workspaceId: 1,
    title: "Finalize hero section",
    status: "In Progress",
    priority: "High",
    due: "Today",
    color: "#f4638a",
  },
  {
    id: 2,
    workspaceId: 1,
    title: "Add project showcase section",
    status: "Todo",
    priority: "High",
    due: "Aug 26",
    color: "#f4638a",
  },
  {
    id: 3,
    workspaceId: 1,
    title: "Write about me section",
    status: "Done",
    priority: "Medium",
    due: "Aug 22",
    color: "#f4638a",
  },
  {
    id: 4,
    workspaceId: 1,
    title: "Add GitHub project links",
    status: "Todo",
    priority: "Medium",
    due: "Aug 27",
    color: "#f4638a",
  },
  {
    id: 5,
    workspaceId: 1,
    title: "Optimize portfolio for mobile",
    status: "In Progress",
    priority: "High",
    due: "Aug 28",
    color: "#f4638a",
  },
  {
    id: 6,
    workspaceId: 1,
    title: "Deploy portfolio",
    status: "Todo",
    priority: "High",
    due: "Aug 30",
    color: "#f4638a",
  },

  // =========================
  // CAPSTONE PROJECT
  // workspaceId: 2
  // =========================

  {
    id: 7,
    workspaceId: 2,
    title: "Build dashboard layout",
    status: "Done",
    priority: "High",
    due: "Aug 23",
    color: "#4d8dfa",
  },
  {
    id: 8,
    workspaceId: 2,
    title: "Implement workspace routing",
    status: "In Progress",
    priority: "High",
    due: "Aug 26",
    color: "#4d8dfa",
  },
  {
    id: 9,
    workspaceId: 2,
    title: "Add task creation form",
    status: "Todo",
    priority: "High",
    due: "Aug 27",
    color: "#4d8dfa",
  },
  {
    id: 10,
    workspaceId: 2,
    title: "Implement Context API",
    status: "Done",
    priority: "Medium",
    due: "Aug 24",
    color: "#4d8dfa",
  },
  {
    id: 11,
    workspaceId: 2,
    title: "Add Redux Toolkit state",
    status: "In Progress",
    priority: "High",
    due: "Aug 28",
    color: "#4d8dfa",
  },
  {
    id: 12,
    workspaceId: 2,
    title: "Implement task filtering",
    status: "Todo",
    priority: "Medium",
    due: "Aug 29",
    color: "#4d8dfa",
  },

  // =========================
  // CONTENT CREATION
  // workspaceId: 3
  // =========================

  {
    id: 13,
    workspaceId: 3,
    title: "Plan next tech video",
    status: "Todo",
    priority: "Medium",
    due: "Aug 27",
    color: "#8a6bf5",
  },
  {
    id: 14,
    workspaceId: 3,
    title: "Write video script",
    status: "In Progress",
    priority: "High",
    due: "Aug 28",
    color: "#8a6bf5",
  },
  {
    id: 15,
    workspaceId: 3,
    title: "Record tutorial",
    status: "Todo",
    priority: "High",
    due: "Aug 30",
    color: "#8a6bf5",
  },
  {
    id: 16,
    workspaceId: 3,
    title: "Edit recorded footage",
    status: "Todo",
    priority: "Medium",
    due: "Sep 01",
    color: "#8a6bf5",
  },
  {
    id: 17,
    workspaceId: 3,
    title: "Create video thumbnail",
    status: "Done",
    priority: "Low",
    due: "Aug 23",
    color: "#8a6bf5",
  },
  {
    id: 18,
    workspaceId: 3,
    title: "Publish video",
    status: "Todo",
    priority: "High",
    due: "Sep 02",
    color: "#8a6bf5",
  },

  // =========================
  // LEARN REACT
  // workspaceId: 4
  // =========================

  {
    id: 19,
    workspaceId: 4,
    title: "Practice useEffect",
    status: "Done",
    priority: "Medium",
    due: "Aug 21",
    color: "#34c98f",
  },
  {
    id: 20,
    workspaceId: 4,
    title: "Learn useRef",
    status: "Done",
    priority: "Medium",
    due: "Aug 24",
    color: "#34c98f",
  },
  {
    id: 21,
    workspaceId: 4,
    title: "Build Context API example",
    status: "In Progress",
    priority: "High",
    due: "Aug 26",
    color: "#34c98f",
  },
  {
    id: 22,
    workspaceId: 4,
    title: "Practice React Router",
    status: "Done",
    priority: "High",
    due: "Aug 23",
    color: "#34c98f",
  },
  {
    id: 23,
    workspaceId: 4,
    title: "Learn React Portals",
    status: "Todo",
    priority: "Medium",
    due: "Aug 29",
    color: "#34c98f",
  },
  {
    id: 24,
    workspaceId: 4,
    title: "Build reusable components",
    status: "In Progress",
    priority: "High",
    due: "Aug 31",
    color: "#34c98f",
  },

  // =========================
  // AI SIDE PROJECT
  // workspaceId: 5
  // =========================

  {
    id: 25,
    workspaceId: 5,
    title: "Research AI API options",
    status: "Done",
    priority: "High",
    due: "Aug 22",
    color: "#f5a623",
  },
  {
    id: 26,
    workspaceId: 5,
    title: "Build AI chat interface",
    status: "In Progress",
    priority: "High",
    due: "Aug 27",
    color: "#f5a623",
  },
  {
    id: 27,
    workspaceId: 5,
    title: "Connect model API",
    status: "Todo",
    priority: "High",
    due: "Aug 28",
    color: "#f5a623",
  },
  {
    id: 28,
    workspaceId: 5,
    title: "Add conversation history",
    status: "Todo",
    priority: "Medium",
    due: "Aug 30",
    color: "#f5a623",
  },
  {
    id: 29,
    workspaceId: 5,
    title: "Test AI responses",
    status: "In Progress",
    priority: "Medium",
    due: "Sep 01",
    color: "#f5a623",
  },
  {
    id: 30,
    workspaceId: 5,
    title: "Deploy AI project",
    status: "Todo",
    priority: "High",
    due: "Sep 04",
    color: "#f5a623",
  },

  // =========================
  // FREELANCE WEBSITE
  // workspaceId: 6
  // =========================

  {
    id: 31,
    workspaceId: 6,
    title: "Finalize client requirements",
    status: "Done",
    priority: "High",
    due: "Aug 22",
    color: "#e85aad",
  },
  {
    id: 32,
    workspaceId: 6,
    title: "Create homepage design",
    status: "Done",
    priority: "High",
    due: "Aug 24",
    color: "#e85aad",
  },
  {
    id: 33,
    workspaceId: 6,
    title: "Build responsive layout",
    status: "In Progress",
    priority: "High",
    due: "Aug 28",
    color: "#e85aad",
  },
  {
    id: 34,
    workspaceId: 6,
    title: "Add contact form",
    status: "Todo",
    priority: "Medium",
    due: "Aug 29",
    color: "#e85aad",
  },
  {
    id: 35,
    workspaceId: 6,
    title: "Connect deployment",
    status: "Todo",
    priority: "High",
    due: "Sep 01",
    color: "#e85aad",
  },
  {
    id: 36,
    workspaceId: 6,
    title: "Send final version to client",
    status: "Todo",
    priority: "High",
    due: "Sep 03",
    color: "#e85aad",
  },

  // =========================
  // JOB PREPARATION
  // workspaceId: 7
  // =========================

  {
    id: 37,
    workspaceId: 7,
    title: "Update resume",
    status: "Done",
    priority: "High",
    due: "Aug 20",
    color: "#5b8def",
  },
  {
    id: 38,
    workspaceId: 7,
    title: "Improve GitHub profile",
    status: "In Progress",
    priority: "Medium",
    due: "Aug 27",
    color: "#5b8def",
  },
  {
    id: 39,
    workspaceId: 7,
    title: "Complete portfolio projects",
    status: "In Progress",
    priority: "High",
    due: "Aug 30",
    color: "#5b8def",
  },
  {
    id: 40,
    workspaceId: 7,
    title: "Practice React interview questions",
    status: "Todo",
    priority: "High",
    due: "Aug 29",
    color: "#5b8def",
  },
  {
    id: 41,
    workspaceId: 7,
    title: "Practice JavaScript problems",
    status: "In Progress",
    priority: "High",
    due: "Sep 01",
    color: "#5b8def",
  },
  {
    id: 42,
    workspaceId: 7,
    title: "Start applying to internships",
    status: "Todo",
    priority: "High",
    due: "Sep 05",
    color: "#5b8def",
  },

  // =========================
  // PERSONAL LEARNING
  // workspaceId: 8
  // =========================

  {
    id: 43,
    workspaceId: 8,
    title: "Learn TypeScript basics",
    status: "Done",
    priority: "Medium",
    due: "Aug 21",
    color: "#20b486",
  },
  {
    id: 44,
    workspaceId: 8,
    title: "Practice async JavaScript",
    status: "Done",
    priority: "Medium",
    due: "Aug 23",
    color: "#20b486",
  },
  {
    id: 45,
    workspaceId: 8,
    title: "Learn REST API design",
    status: "In Progress",
    priority: "High",
    due: "Aug 28",
    color: "#20b486",
  },
  {
    id: 46,
    workspaceId: 8,
    title: "Learn Node.js fundamentals",
    status: "Todo",
    priority: "High",
    due: "Sep 01",
    color: "#20b486",
  },
  {
    id: 47,
    workspaceId: 8,
    title: "Build a small Express API",
    status: "Todo",
    priority: "High",
    due: "Sep 03",
    color: "#20b486",
  },
  {
    id: 48,
    workspaceId: 8,
    title: "Review JavaScript fundamentals",
    status: "In Progress",
    priority: "Medium",
    due: "Aug 30",
    color: "#20b486",
  },
];